### ISSUE TITLE
Unable to import image

### ISSUE THREAD

**Issue by BraveCaperCat** [fonnymunkey/BQ_Multiblock_Structure_Integration#4]
I am unable to import an image for a multiblock

**Comment by BraveCaperCat** [comment]
Here's my image:
![Uploading lathe.png…]()
I tried referencing it with:
crashedpack/lathe.png,
lathe.png,
lathe

**Comment by BraveCaperCat** [comment]
Dimensions:
1920X1057
File size:
355KB

**Comment by BraveCaperCat** [comment]
It's just pink and black squares, which usually means missing texture

**Comment by BraveCaperCat** [comment]
Which means that.............................................................THE IMAGE IS NOT LOADING

**Comment by fonnymunkey** [comment]
The image location for each task is defined the same way BQ's home image is, as "<packname>:<example/path/image>" with the packname being whatever you defined in BQ's settings, and the path being the location inside BQ's config folder.

**Comment by BraveCaperCat** [comment]
> being whatever you defined in BQ's settings

OH

**Comment by BraveCaperCat** [comment]
That is what i did not hear

**Comment by BraveCaperCat** [comment]
where is that config

**Comment by BraveCaperCat** [comment]
> where is that config

**Comment by fonnymunkey** [comment]
BQ's config folder? The folder named "betterquesting" in the config folder

**Comment by BraveCaperCat** [comment]
Only thing under that, is "Resources"

**Comment by BraveCaperCat** [comment]
And the config to set modpack name!

**Comment by BraveCaperCat** [comment]
No .cfg files like other mods,
this must be a third party issue (Better Questing)
